Svg logo, sticky header, new socialmedia icons
Aspoz/runcmd pull request #4
Opened 2016-09-23 12:51 UTC by ericfennis

- Svg logo added to the header
- The header is now sticky and show up when scroll to top
- Socialmedia icons are svg now
- New header html added to al pages

2016-09-24 13:00 UTC, Aspoz commented on app/styles/objects/_header.sass
> +      top: -96px
change to 6rem

2016-09-24 13:00 UTC, Aspoz commented on app/styles/objects/layouts/_base.sass
> +  margin-top: 96px
change to 6rem

2016-09-24 13:01 UTC, Aspoz commented on app/vacature.html
> +       <div class="header">
whitespace

2016-09-24 13:01 UTC, Aspoz commented on app/vacaturebank.html
> +       <div class="header">
whitespace

2016-09-24 13:01 UTC, Aspoz commented on app/wiezijnwij.html
> +       <div class="header">
whitespace

2016-09-24 13:03 UTC, Aspoz commented on npm-debug.log
> +0 info it worked if it ends with ok
what is this?
if this keeps appearing on windows perhaps putting this file in gitignore will be better

2016-09-24 13:05 UTC, Aspoz commented on app/scripts/main.js
> +}		);
add a new line to every file, this is needed for better git commits
There is also an option in sublime for adding a newline add the end of a file on save

2016-09-24 13:05 UTC, Aspoz commented on app/scripts/main.js
> +$(function() {
inconsistent indenting

2016-09-24 13:13 UTC, sndrgrdn requested changes
Overall the navigation works great, it only feels a little slow to show when scrolling up.
The Facebook social icon color seems a little off.

2016-09-24 13:13 UTC, sndrgrdn commented on app/contact.html
> +       <div class="header">
Remove whitespace, there is a setting a sublime that will do this for you

2016-09-24 13:13 UTC, sndrgrdn commented on app/events-borrel-28sept.html
> +       <div class="header">
whitespace

2016-09-24 13:13 UTC, sndrgrdn commented on app/events.html
> +       <div class="header">
whitespace

2016-09-24 13:13 UTC, sndrgrdn commented on app/index.html
> +      <div class="header">
whitespace

2016-09-24 13:13 UTC, sndrgrdn commented on app/lidworden.html
> +       <div class="header">
whitespace

2016-09-24 13:13 UTC, sndrgrdn commented on app/nieuws.html
> +       <div class="header">
whitespace

2016-09-25 16:19 UTC, ericfennis commented
Thanks for the feedback!
Can you take a look at the last commit?

2016-09-26 09:19 UTC, sndrgrdn approved these changes

2016-09-26 09:19 UTC, merged